name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test (.NET 7)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore StreetBackend/StreetBackend.sln

      - name: Build the solution
        run: dotnet build StreetBackend/StreetBackend.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test StreetBackend.Test/StreetBackend.Test.csproj --no-build --configuration Release --logger trx
